# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b2a8858ef55c49a9b62eb66ed7f9fb090e22f55f62dbeff1c43aa7c0d11ba3c090bd8151119d73c0177de3a1b6ba121236e32713ef4e83409df869551d7f45

test:
  secret_key_base: a6a99d28254ff0f4563e3620d42c6361226fd071a80e6af7b9c3302e8b7dff9e9b11282522b58ef116c48b059b060c18720ab34620c63047836b9f12b2941a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
